media_locale = {}

_NEW_PARTICIPANT = {
    'ADD_HUMAN_TITLE': 'Agregar una nueva fuente humana',
    'SEL_AGE_RANGE': 'Seleccione el rango de edad del participante:',
    'AGE_0_6': '3 meses - 6 años',
    'AGE_7_12': '7-12 años',
    'AGE_13_17': '13-17 años',
    'AGE_18': '18+ años',

    'PARTICIPATION_AGREEMENT': '''<p style="text-align: center;font-weight: bold;">AMERICAN GUT PROJECT</p>
<p style="text-align: center;font-weight: bold;">The Microsetta Initiative</p>
<p style="text-align: center;font-weight: bold;">University of California, San Diego</p><br>
<p style="text-align: center;font-weight: bold;">ACUERDO DE PARTICIPACIÓN</p></b>
<ol><li><b>Indemnización.</b> Cada parte defenderá, indemnizará y eximirá de responsabilidad a la otra parte, a sus funcionarios, empleados y agentes de y contra cualquier y toda responsabilidad, pérdida, gasto (incluidos los honorarios de abogados) y reclamos por lesiones o daños que surjan del cumplimiento de este Acuerdo, pero solo en proporción a y en la medida en que dicha responsabilidad, pérdida, gasto, honorarios de abogados , o las reclamaciones por lesiones (incluida la muerte) o daños son causados por o como resultado de los actos u omisiones negligentes o intencionales de la parte indemnizadora, sus funcionarios, empleados o agentes.</li>
<li><b>Indemnización por infracción de patentes.</b> El Individuo indemnizará, defenderá y eximirá de responsabilidad a UCSD, sus funcionarios, agentes y empleados contra todas las pérdidas, daños, responsabilidades, costos y gastos (incluidos, entre otros, los honorarios de abogados) que resulten de cualquier juicio o procedimiento en el que se determine, o cualquier acuerdo de conciliación que surja de la alegación, que el Individuo suministre o suministre piezas a UCSD , bienes, componentes, programas, prácticas o métodos bajo este Acuerdo o el uso de UCSD de tales partes, materiales, bienes, componentes, programas, prácticas o métodos suministrados por el Individuo bajo este Acuerdo constituye una infracción de cualquier patente, derecho de autor, marca registrada, nombre comercial, secreto comercial u otro derecho de propiedad o contractual de cualquier tercero. UCSD se reserva el derecho de participar en la defensa contra cualquier demanda o acción de este tipo.</li>
<li><b>Limitación de responsabilidad.</b> EXCEPTO CON RESPECTO A SUS OBLIGACIONES DE INDEMNIZACIÓN, NINGUNA DE LAS PARTES SERÁ RESPONSABLE ANTE LA OTRA PARTE POR DAÑOS INDIRECTOS, ESPECIALES, INCIDENTALES, EJEMPLARES O CONSECUENTES, O COSTOS, INCLUIDOS, ENTRE OTROS, CUALQUIER PÉRDIDA DE GANANCIAS O INGRESOS, INCLUSO SI DICHA PARTE HA SIDO ADVERTIDA DE LA POSIBILIDAD DE TALES DAÑOS E INDEPENDIENTEMENTE DE LA TEORÍA LEGAL BAJO LA CUAL SE BUSCAN DICHOS DAÑOS. UCSD NIEGA TODAS LAS GARANTÍAS, EXPRESAS E IMPLÍCITAS, INCLUIDAS LAS GARANTÍAS DE COMERCIABILIDAD E IDONEIDAD PARA UN PROPÓSITO PARTICULAR. EN NINGÚN CASO LA RESPONSABILIDAD TOTAL DE UCSD BAJO ESTE ACUERDO EXCEDERÁ LA CANTIDAD PAGADA POR EL INDIVIDUO POR LOS SERVICIOS. UCSD NO GARANTIZA UN RESULTADO ESPECÍFICO O ENTREGABLE PARA PARTICIPAR EN ESTE PROYECTO.</li>
<li><b>Propiedad de materiales de UCSD.</b> UCSD será el propietario de los productos finales al recibir los materiales del Individuo.</li>
<li><b>Uso del nombre UCSD.</b> La Sección 92000 del Código de Educación de California prohíbe el uso del nombre de la Universidad de California en San Diego para sugerir que UCSD respalda un producto o servicio. El Individuo no usará el nombre de la Universidad de California, o cualquier acrónimo del mismo.</li>
<li><b>Retraso excusable.</b> En el caso de un retraso causado por inclemencias del tiempo, incendio, inundación, huelga u otro conflicto laboral, actos de Dios, actos de funcionarios o agencias gubernamentales, o cualquier otra causa fuera del control de UCSD, el desempeño de UCSD se excusa en virtud del presente por los períodos de tiempo atribuibles a dicho retraso, que puede extenderse más allá del tiempo perdido debido a una o más de las causas mencionadas anteriormente. El deber de la Compañía de pagar por los costos pasados o continuos no se suspende en virtud del presente.</li>
<li><b>No interferencia.</b> A pesar de cualquier otra disposición contenida en este documento, el uso de las instalaciones de UCSD y / o el personal de UCSD en apoyo de este Acuerdo solo puede autorizarse en la medida en que no interfiera con el trabajo relacionado con las misiones principales de UCSD y / o el Departamento (por ejemplo, educación e investigación). En consecuencia, el recurso exclusivo del Individuo para el incumplimiento por parte de UCSD o de las personas que actúan en su nombre para realizar servicios o proporcionar información o datos en virtud del presente en un momento determinado o de cualquier manera específica, se limita al reembolso de cualquier pago no utilizados en virtud de este Acuerdo.</li>
<li><b>Naturaleza no exclusiva de los servicios.</b> Los Servicios aquí descritos se ofrecen al individuo de forma no exclusiva. Nada de lo aquí expuesto se interpretará como la concesión a la Compañía de ningún derecho exclusivo sobre los Servicios a los que se hace referencia en este documento, y UCSD se reserva el derecho de ofrecer y realizar Servicios similares o idénticos para otros.</li>
<li><b>Noticia.</b> Cualquier notificación o comunicación requerida por este Acuerdo se hará por escrito y se considerará que ha sido debidamente dada si se entrega personalmente, o se envía por correo de entrega inmediata, o correo certificado prepagado, correo electrónico o transmisión por facsímil confirmada, dirigida a la otra parte en la dirección establecida en el registro del kit, o en cualquier otra dirección que dicha parte pueda especificar en lo sucesivo por escrito a la otra parte.</li>
<li><b>Situación de las Partes.</b> Este Acuerdo no tiene la intención de crear, ni se interpretará como, una empresa conjunta, asociación, consorcio, franquicia u otra forma de relación comercial. Ninguna de las partes tendrá, ni se considerará que tiene, ningún derecho, poder o autoridad para asumir, crear o incurrir en ningún gasto, responsabilidad u obligación en nombre de la otra parte, excepto según lo dispuesto expresamente en este documento.</li>
<li><b>Tercero beneficiario.</b> No hay terceros beneficiarios previstos de este Acuerdo.</li>
<li><b>Divisibilidad.</b> Si alguna disposición de este Acuerdo se considera inválida, ilegal o inaplicable en cualquier aspecto, dicha disposición se tratará como separable, dejando las disposiciones restantes intactas, siempre que ello no perjudique materialmente a ninguna de las partes en sus respectivos derechos y obligaciones contenidos en los términos, convenios o condiciones válidos.</li>
<li><b>No renuncia.</b> El hecho de que cualquiera de las partes no exija el cumplimiento de cualquiera de los términos de este Acuerdo o la renuncia por cualquiera de las partes de cualquier incumplimiento en virtud de este Acuerdo no impedirá una aplicación posterior de dicho término, ni se considerará una renuncia a cualquier incumplimiento posterior.</li>
<li><b>Modificación del Acuerdo.</b> Este Acuerdo se modificará únicamente mediante acuerdo escrito de las partes.</li>
<li><b>Ley aplicable.</b> Este Acuerdo se regirá por las leyes del Estado de California sin tener en cuenta sus disposiciones sobre conflictos de leyes.</li>
<li><b>Firmas, Contrapartes y Copias.</b> El presente Acuerdo podrá ejecutarse en contrapartes, todas las cuales, en su conjunto, constituirán un contrato con la misma fuerza y efecto que si todas las firmas se hubieran introducido en un documento. Las firmas podrán hacerse electrónicamente, haciendo clic en "Acepto" y dichas firmas electrónicas serán válidas y vinculantes para las partes que las hagan, y servirán en todos los aspectos como firmas originales. Al hacer clic en "Acepto", este acuerdo se considerará totalmente ejecutado por ambas partes. Las firmas pueden entregarse entre las partes por fax o por medios electrónicos. A partir de entonces, las partes acuerdan además que las copias electrónicas de este Acuerdo pueden ser utilizadas para todos y cada uno de los fines para los cuales el original puede haber sido utilizado.</li>
<li><b>Arbitraje.</b> En el caso de cualquier disputa, reclamo, pregunta o desacuerdo que surja de o esté relacionado con este Acuerdo o el incumplimiento del mismo, las partes del presente deberán hacer todo lo posible para resolver la disputa, reclamo, pregunta o desacuerdo. A tal efecto, se consultarán y negociarán entre sí de buena fe y reconociendo sus intereses mutuos, tratando de llegar a una solución justa y equitativa satisfactoria para ambas partes. Si no llegan a una solución dentro de un período de sesenta (60) días, entonces, previa notificación de cualquiera de las partes a la otra, todas las disputas, reclamos, preguntas o desacuerdos se resolverán finalmente de acuerdo con las disposiciones de la Asociación Americana de Arbitraje ("AAA") y procederán bajo las disposiciones del Título 9 de las Secciones 1280 del Código de Procedimiento Civil de California a través de e incluyendo 1294.2. Las disposiciones de descubrimiento de la Sección 1283.05 del Código de Procedimiento Civil de California serán aplicables a este Acuerdo. Cada parte cargará con sus propias costas.</li>
<li><b>Control de exportaciones.</b> No se entregarán a UCSD materiales ITAR o materiales controlados de exportación de conformidad con este acuerdo.</li>
<li><b>Acuerdo completo.</b> Este Acuerdo, incluido el Anexo A hecho una parte del mismo, establece el acuerdo completo de las partes con respecto al tema aquí tratado y reemplaza cualquier acuerdo anterior, oral y escrito, y todas las demás comunicaciones entre las partes con respecto a dicho tema.</li>
</ol><br/>''',

    'EXHIBIT_A': '''<p style="text-align: center;font-weight: bold;">ANEXO A</p>
<p style="text-align: center;font-weight: bold;">DECLARACIÓN DE SERVICIOS DEL PROYECTO AMERICAN GUT</p>
<ol>
<li><b>DESCRIPCION DE TRABAJO:</b>
<p>Los Servicios se realizarán como se establece a continuación o de acuerdo con el anexo del presente y se incorporarán por referencia en este documento.</p>
<p>Cuando se inscribe en el estudio, puede reclamar un paquete de análisis de investigación basados en su nivel de contribución. Se le envía por correo un kit con instrucciones de muestreo e instrucciones sobre cómo iniciar una sesión en el sitio web para completar el formulario de consentimiento y enviar el cuestionario. Cualquier muestra que se reciba en el laboratorio sin un formulario de consentimiento completado en línea no se secuencia. Usted será capaz de ver, descargar e imprimir un certificado de alta resolución adecuado para el enmarcado de sus resultados y el acceso a un informe de taxones más detallado de sus resultados - que se puede ver en línea y descargar en Excel.</p>
<p>He aceptado esta descripción de trabajo en nombre de UCSD y la responsabilidad de administrar y supervisar el acuerdo.</p>
</li>
<li><b>Productos de Entrega:</b>
<p>Aproximadamente 8-10 semanas después de haber recibido su muestra, se le notificará de sus resultados electrónicamente.</p>
</li>
<li><b>COSTO:</b> El costo es variable en función del nivel de contribución que se eligió.
</li>
<li><b>PAGO</b></li>
<ol><li><b>PROGRAMA DE PAGO:</b> 100% del costo adeudado al hacer clic en "Acepto"</li>
<li><b>REMESA:</b> El pago se enviará a través de PayPal a través del sitio web de FundRazr.</li>
</ol>
<li><b>TÉRMINO DEL ACUERDO:</b> Este Acuerdo entrará en vigencia a partir de la fecha de envío del pago a FundRazr.</li>
<li><b>CONTACTO DEL OFICIAL DE CONTRATO DE UCSD:</b><br/>
Karim Hussein<br/>
University of California, San Diego<br/>
9500 Gilman Drive Mail Stop 0934<br/>
La Jolla, California 92093-0934<br/>
Teléfono: (858) 822-5180<br/>
Correo electrónico: khussein@ucsd.edu''',
    'BILL_OF_RIGHTS': '''Declaración de derechos del sujeto experimental''',
    'TEXT_I_HAVE_READ_1': 'He leído (o alguien me ha leído) este formulario. Soy consciente de que se me pide que participe en un estudio de investigación. Acepto voluntariamente participar en este estudio.',
    'TEXT_I_HAVE_READ_SIMPLIFIED': 'Sí, estarás en este estudio de investigación.',
    'PERSON_ATTAINING_ASSENT': 'Firma de la persona que obtiene el consentimiento',
    'TEXT_ASSENT_WITNESS': 'A mi juicio, el participante está dando su consentimiento voluntaria y conscientemente y posee la capacidad legal de dar su consentimiento para participar en el estudio.',
    'OBTAINER_NAME': 'Nombre de la persona que obtiene el consentimiento',
    'TEXT_I_HAVE_READ_PARENT': 'He leído (o alguien me ha leído) este formulario. Soy consciente de que se le está pidiendo a mi hijo que participe en un estudio de investigación. Acepto voluntariamente que mi hijo participe en este estudio',
    'PARTICIPANT_NAME': 'Nombre del participante',
    'PARTICIPANT_PARENT_1': 'Nombre del Padre de Familia / Guardian',
    'PARTICIPANT_PARENT_2': 'Nombre del padre / tutor del segundo padre',
    'PARTICIPANT_DECEASED_PARENTS': 'Uno de los padres / tutor ha fallecido o no puede dar su consentimiento',
    'DATE_SIGNED': 'Fecha firmada',
    'PARTICIPANT_ADDRESS': 'Dirección del participante',
    'PARTICIPANT_CITY': 'Ciudad participante',
    'PARTICIPANT_STATE': 'Estado participante',
    'PARTICIPANT_ZIPCODE': 'Código postal del participante',
    'PARTICIPANT_COUNTRY': 'País participante',

    'CONSENT_YOUR_CHILD': '''
        <p align='center'><b>University of California, San Diego</b><br/>
        Consentimiento de los padres para que su hijo participe como sujeto en una investigación<br/></p>
        <p align='center' style='font-weight: bold;'>Proyecto American Gut</p>
        <p style='font-weight: bold;'><i>¿Quién realiza el estudio, por qué se le ha pedido a su hijo que participe, cómo se ha seleccionado a su hijo y cuál es la cifra aproximada de participantes en el estudio?</i></p>
        <p>El Dr. Rob Knight está realizando un estudio para saber más sobre los billones de bacterias y otros organismos (denominados “microbioma”) que viven dentro de su cuerpo y en la superficie de este. Usted ha inscrito voluntariamente a su hijo en este estudio porque quiere saber más sobre su microbioma. Los niños, como los demás seres humanos, tienen un microbioma único. Incluirlos en el estudio ayudará a definir el desarrollo del microbioma. En el estudio participarán unas 100 000 personas de todo EE. UU. y de otros países.</p>
        <p style='font-weight: bold;'><i>¿Por qué se está llevando a cabo este estudio?</i></p>
        <p>El objetivo del estudio es evaluar con mayor precisión las diferencias entre las personas y determinar si dichas diferencias pueden atribuirse al modo de vida, a la dieta, al tipo de constitución corporal, a la edad o a la presencia de enfermedades relacionadas. Los resultados se utilizarán para crear una base de datos que contendrá secuencias y metabolitos de distintas zonas del cuerpo (p. ej., la piel, la boca, el estómago y los intestinos), y detalles del niño participante que provee la muestra. Otros investigadores podrán usar estos datos cuando estén estudiando el mismo tipo de muestra en otros estudios científicos (p. ej., ciertas enfermedades en las que sean comnes las anomalías del estómago y los intestinos). </p>
        <p style='font-weight: bold;'>¿Qué le sucederá a su hijo durante el estudio, y qué procedimientos forman parte de la atención estándar y cuáles son experimentales?</p>
        <p>Se le pregunta si desea que su hijo participe en este estudio porque usted se registró en el sitio web de American Gut para un análisis microbiológico. Cuando se registró, le enviamos un kit de toma de muestras junto con las instrucciones de inicio de sesión en el sitio web, de modo que pueda dar su consentimiento formal para el estudio.</p>
        <p>Analizaremos todas las muestras para las que se hayan completado el formulario de consentimiento y el cuestionario. Se analizarán las muestras suministradas para el proyecto (incluidas las de su hijo) y los resultados se publicarán en artículos científicos en los que se definirá la diversidad del microbioma humano. Se le enviará un enlace a través del que podrá ver, descargar e imprimir diagramas en alta resolución —aptos para enmarcar— de sus resultados y acceder a un informe detallado sobre los taxones encontrados.</p>
        <p>A través de este consentimiento, queremos que comprenda lo que haremos con la muestra de su hijo y lo que usted obtendrá a cambio.</p>
        <p>Le pediremos que responda un cuestionario en línea sobre el modo de vida y los hábitos alimentarios de su hijo. Calculamos que no deberá llevarle más de 30 minutos. A continuación, tomará una muestra de una parte del cuerpo de su hijo (de interés para usted) con algo semejante a un bastoncillo de algodón estéril frotándolo por la piel o la lengua. También puede tomar una muestra de las heces de una de las siguientes tres formas:</p>
        <ol>
        <li>Inserte las puntas del bastoncillo en papel higiénico usado y devuelva la muestra en la funda de plástico suministrada.</li>
        <li>Inserte las puntas del bastoncillo en papel higiénico usado, pase las puntas por la superficie de una tarjeta para pruebas de sangre oculta en las heces y devuélvanos la tarjeta. La tarjeta para pruebas de sangre oculta en las heces es el mismo instrumento que utiliza el médico para verificar si hay sangre en las heces. La tarjeta para pruebas de sangre oculta en las heces permite estabilizar las heces para su posterior análisis. No verificaremos si hay sangre en las heces con fines diagnósticos, puesto que no somos un laboratorio clínico.</li>
        <li>Envíe una muestra completa de heces refrigeradas con hielo (cuando se solicite, para realizar otros análisis) en el recipiente para envíos que le suministraremos. Dicho recipiente contiene una serie de compresas de hielo que enfriarán la muestra de manera fiable a -20 °C/-4 °F.</li>
        </ol>
        <p>También puede tomar muestras de otras partes del cuerpo, como el oído, la nariz, la vagina, el cuero cabelludo o la planta del pie.</p>
        <p>Debe enviarnos los bastoncillos o las tarjetas para pruebas de sangre oculta en las heces en el sobre suministrado y a través del servicio regular de correo nacional. Las muestras de heces completas deben enviarse a los laboratorios Knight Lab en el recipiente para envíos suministrado.</p>
        <p>Se extraerá el ADN de la muestra, que se amplificará mediante PCR (reacción en cadena de la polimerasa) y se secuenciará para ver qué bacterias contiene la muestra y en qué proporción. Es posible que utilicemos el resto de la muestra para analizar los metabolitos, como las proteínas, o las sustancias químicas derivadas de las bacterias o para analizar en mayor detalle bacterias específicas que nos resulten de interés. Creemos que tardaremos unos dos meses en conocer los resultados del cálculo inicial de la diversidad bacteriana.</p>
        <p>Los resultados se cargarán en su cuenta de American Gut en cuanto estén disponibles.</p>
        <p>Le pedimos también que nos autorice a utilizar la muestra de su hijo o el ADN no humano extraído de dicha muestra (p. ej., el ADN de las bacterias) en futuros estudios. Además, queremos solicitarle su consentimiento para ponernos en contacto con usted por correo electrónico para solicitar más información como seguimiento a las preguntas sobre su hijo que haya respondido en el cuestionario.</p>
        <p style='font-weight: bold;'>Atención: La secuenciación no tiene fines diagnósticos y no está dirigida al ADN humano.>
        <p style='font-weight: bold;'>¿Cuánto tiempo es necesario para realizar cada procedimiento del estudio, cuánto tiempo debe dedicar en total su hijo y cuánto durará el estudio?</p>
        <p>Tardará 30 minutos o menos en responder el cuestionario en línea. Tardará 5 minutos o menos en tomar cada una de las muestras que vaya a suministrar. En principio, el estudio durará 5 años. No obstante, los resultados estarán a su disposición antes de que este termine (por lo general, en un plazo de 2 meses después de que recibamos la muestra). Puede optar por tomar muestras de su hijo en más de una ocasión. Si los datos personales de su hijo (p. ej., su dirección o estado de salud) cambian, le pedimos que vuelva a introducir voluntariamente los datos de contacto y/o las respuestas del cuestionario.</p>
        <p style='font-weight: bold;'>¿Cuáles son los riesgos relacionados con este estudio?</p>
        <p>Las técnicas de toma de muestras se usan desde hace más o menos 10 años y no se han notificado efectos secundarios al respecto. No examinamos el ADN humano que haya en la muestra, por lo que no obtendremos información personal sobre el genoma. Antes de consignar datos en archivos de acceso público se eliminan todos los datos conocidos de la secuencia humana. El personal del estudio ha tomado precauciones para garantizar que el riesgo de pérdida de la confidencialidad sea mínimo. Si se pusiera en riesgo la confidencialidad, las consecuencias para su hijo serían mínimas, pues los resultados no son diagnósticos y no repercuten en la decisión de las aseguradoras de darle o no cobertura a su hijo.</p>
        <p><i>(Por lo general, las leyes federales y estatales consideran que es ilegal que las aseguradoras, las aseguradoras para grupos y la mayor parte de los empleadores le discriminen por su información genética. Por norma general, dichas leyes lo protegen de las siguientes formas: a) las aseguradoras y las aseguradoras para grupos no pueden solicitarnos la información genética que obtengamos sobre usted en esta investigación; b) las aseguradoras y las aseguradoras para grupos no pueden usar su información genética para tomar decisiones sobre sus opciones de cobertura o pagos por seguro; c) los empleadores que tengan cinco empleados o más no pueden usar la información genética que obtengamos sobre usted en esta investigación para tomar decisiones de contratación, ascenso o despido ni para definir condiciones laborales.)</i></p>
        <p>Dado que este es un estudio de investigación, puede haber riesgos desconocidos que no podemos prever. Le informaremos de cualquier novedad importante al respecto.</p>
        <p style='font-weight: bold;'>¿Cuáles son las alternativas a no participar en este estudio?</p>
        <p>El estudio es completamente voluntario, y si no permite que su hijo participe no tendrá que hacer frente a ninguna consecuencia. No hay pruebas alternativas.</p>
        <p style='font-weight: bold;'>¿Cuáles beneficios podrían anticiparse razonablemente?</p>
        <p>Su hijo no obtendrá ningún beneficio directo por participar en este estudio. De cualquier modo, el investigador puede obtener más información sobre el microbioma humano en situaciones de buena salud y de enfermedad, lo que podría resultar valioso para los investigadores de otros estudios.</p>
        <p style='font-weight: bold;'>¿Puede decidir que su hijo no participe o se retire del estudio sin recibir sanciones ni perder beneficios?</p>
        <p>Ni usted ni su hijo obtendrán ningún beneficio directo por participar en este estudio. Creemos que tal vez sienta curiosidad natural por saber qué bacterias contiene su muestra cómo es en comparación con las muestras de otras personas del mismo sexo y edad. De cualquier modo, el investigador obtendrá más información sobre el microbioma humano en situaciones de buena salud y de enfermedad, lo que podría resultar valioso para los investigadores de otros estudios. Tal vez pueda deducir de sus impuestos la contribución al proyecto. Fundrazr, que se encarga de todas las contribuciones financieras, le enviará un recibo.</p>
        <p>Analizaremos todas las muestras para las que se hayan completado el formulario de consentimiento y el cuestionario. Se analizarán las muestras del proyecto (incluidas las de su hijo) y los resultados se publicarán en un artículo científico. Se le enviará un enlace a través del que podrá ver, descargar e imprimir diagramas en alta resolución de sus resultados, aptos para enmarcar, y acceder a un informe detallado sobre los taxones encontrados.</p>
        <p>Ni usted ni su médico pueden utilizar los resultados del análisis para confirmar diagnósticos clínicos; no realizamos pruebas de detección de enfermedades infecciosas.</p>
        <p style='font-weight: bold;'>¿Se puede retirar a su hijo del estudio sin su consentimiento?</p>
        <p>La participación en el estudio es completamente voluntaria. Puede negarse a que su hijo participe o hacer que su hijo se retire del estudio en cualquier momento, sin tener que recibir sanciones ni perder los beneficios que le correspondan. Si decide que no desea que su hijo siga participando en el estudio, se le pedirá que se comunique a la línea de asistencia del proyecto American Gut para comunicarnos su intención de que el niño abandone el estudio. Si no se ha procesado la muestra, puede solicitar un reembolso, que se tramitará en el sitio mediante el que realizó su contribución al proyecto.</p>
        <p>Se le notificará cualquier información importante obtenida durante el transcurso del estudio y que pueda afectar a su voluntad de que su hijo siga participando.</p>
        <p style='font-weight: bold;'>¿Se le pagará por participar en este estudio?</p>
        <p>No recibirá ninguna remuneración económica por participar en este estudio.</p>
        <p style='font-weight: bold;'>¿Hay algún gasto vinculado con la participación en el estudio?</p>
        <p>Una vez que se haya inscrito en el proyecto y haya enviado por correo su muestra, no tendrá que pagar nada por participar en el estudio.</p>
        <p style='font-weight: bold;'>¿Qué sucede si su hijo sufre una lesión como consecuencia directa del estudio?</p>
        <p>Si su hijo sufre una lesión como consecuencia directa de su participación en este estudio, la Universidad de California le prestará toda la atención médica necesaria para su tratamiento. Esta universidad no ofrecerá ningún otro tipo de indemnización a su hijo por lesiones. Para saber más sobre este tema, usted o su hijo pueden llamar a la oficina del Programa de protección para investigaciones con seres humanos al 858-246-4777 para consultar sobre sus derechos como sujeto de investigación o denunciar problemas relacionados con el estudio.</p>
        <p style='font-weight: bold;'>¿Y la confidencialidad?</p>
        <p>Se protegerá la confidencialidad de los registros de la investigación en la medida que lo permita la ley. Todos los datos sobre su hijo que se introduzcan en el sitio web se guardarán en un servidor protegido por contraseña ubicado en el SDSC (San Diego Supercomputer Center), que se encuentra en la UCSD y cuenta con acceso controlado por características biométricas. Los datos financieros de los participantes que contribuyan al proyecto no se pondrán a disposición de los investigadores. El código (que vincula los datos personales del participante con los códigos de barras de las muestras) se guarda en otro servidor protegido por contraseña, al que solo pueden acceder el investigador principal, el investigador secundario, el coordinador de las muestras y los programadores de la base de datos. Todos los análisis se realizan con datos anonimizados; los datos que se consignan en archivos públicos para uso de otros investigadores también se anonimizan. La Junta de Revisión Institucional de la UCSD podrá revisar los registros del estudio.</p>
        <p>Tendrá que presentar datos a través de los que se le podría identificar si se publicaran, como su nombre, su edad, su fecha de nacimiento y su dirección. Hemos hecho todo lo posible para garantizar que nadie pueda identificarle a partir de los datos personales que suministre, pero conservamos información fundamental, como su sexo y su edad, sin poner en riesgo sus datos personales ni la integridad de estos.</p>
        <p>Es posible que debamos denunciar incidentes confirmados o sospechas razonables de maltrato o abandono de niños, adultos dependientes o personas mayores, incluidos el maltrato físico o emocional, el abuso sexual o económico y el abandono. El único modo en que podríamos descubrir dicho maltrato es que lo denuncie el propio participante o su tutor legal, por lo que no es probable que suceda. Si los investigadores se percatan de este tipo de información, podrán denunciarla ante las autoridades pertinentes.</p>
        <p style='font-weight: bold;'>¿A quién puede llamar si tiene alguna duda?</p>
        <p>Si tiene alguna duda o problemas relacionados con la investigación, puede llamar a Rob Knight al 858-246-1184 o a Dominic Nguyen al 858-534-8739.</p>
        <p>Puede llamar a la oficina del Programa de protección para investigaciones con seres humanos al 858-246-4777 para consultar acerca de sus derechos como sujeto de investigación o denunciar cualquier problema relacionado con el estudio.</p>
        <p style='font-weight: bold;'>Firma y consentimiento</p>
        <p>Ha recibido una copia de este documento de consentimiento y una copia de la “Declaración de derechos del sujeto experimental”, para que las conserve.</p>
        <p>Autoriza a su hijo a participar.</p>''',
    'CONSENT_18': '''
        <p align='center'><b>University of California, San Diego</b><br/>
        Consentimiento para participar como sujeto de investigación</p>
        <p style='font-weight: bold;' align='center'>Proyecto American Gut</p>
        <p style='font-weight: bold;'><i>¿Quién realiza el estudio, por qué se le ha pedido que participe, cómo fue seleccionado y cuál es la cifra aproximada de participantes en el estudio?</i></p>
        <p>El Dr. Rob Knight está realizando un estudio de investigación para saber más sobre los billones de bacterias y otros organismos (denominados “microbioma”) que viven dentro de su cuerpo y en su superficie. Le hemos pedido que participe en este estudio porque posee un microbioma único, distinto al del resto del mundo. En el estudio participarán unas 100 000 personas de todos los EE. UU. y otros países.</p>
        <p style='font-weight: bold;'><i>¿Por qué se está llevando a cabo este estudio?</i></p>
        <p>El objetivo del estudio es evaluar con mayor precisión las diferencias entre las personas y determinar si dichas diferencias pueden atribuirse al modo de vida, a la dieta, al tipo de constitución corporal, a la edad o a la presencia de enfermedades relacionadas. Los resultados se utilizarán para crear una base de datos que contendrá secuencias y metabolitos de distintas zonas del cuerpo (p. ej., la piel, la boca o el estómago), así como detalles de los participantes que provean las muestras que otros investigadores podrán usar cuando necesiten muestras para compararlas al estudiar el mismo tipo de muestra en otros estudios científicos, p. ej., ciertas enfermedades en las que sean comunes las anomalías del estómago y los intestinos.</p>
        <p style='font-weight: bold;'><i>¿Qué le sucederá durante el estudio?</i></p>
        <p>Se le ha pedido que participe en este estudio porque se registró en el sitio web de American Gut (estudio sobre el estómago y los intestinos de los estadounidenses) para un análisis microbiológico. Cuando se registró, le enviamos un kit de toma de muestras junto con las instrucciones de inicio de sesión en el sitio web, de modo que pueda dar su consentimiento formal para participar en el estudio.</p>
        <p>Analizaremos todas las muestras para las que se hayan completado el formulario de consentimiento y el cuestionario. Se analizarán las muestras suministradas para el proyecto (incluidas las suyas) y los resultados se publicarán en artículos científicos en los que se definirá la diversidad del microbioma humano. Se le enviará un enlace a través del que podrá ver, descargar e imprimir diagramas en alta resolución de sus resultados —aptos para enmarcar— y acceder a un informe más detallado sobre los taxones encontrados. A través de este consentimiento queremos que comprenda lo que haremos con la muestra y lo que usted obtendrá a cambio.</p>
        <p>Le pediremos que complete un cuestionario en línea sobre su modo de vida y sus hábitos alimentarios. Calculamos que no deberá llevarle más de 30 minutos. A continuación, le pediremos que tome una muestra de una parte de su cuerpo (de interés para usted) con algo semejante a un bastoncillo de algodón estéril frotándolo por la piel o la lengua. También puede tomar una muestra de sus heces de una de las siguientes tres formas:</p>
        <ol>
        <li>Inserte las puntas del bastoncillo en papel higiénico usado y devuelva la muestra en la funda de plástico suministrada.</li>
        <li>Inserte las puntas del bastoncillo en papel higiénico usado, pase las puntas por la superficie de una tarjeta para pruebas de sangre oculta en las heces y devuélvanos la tarjeta. La tarjeta para pruebas de sangre oculta en las heces es el instrumento que utiliza el médico para verificar si hay sangre en las heces. La tarjeta para pruebas de sangre oculta en las heces permite estabilizar las heces para su posterior análisis. No verificaremos si hay sangre en las heces con fines diagnósticos, puesto que no somos un laboratorio clínico.</li>
        <li>Envíe una muestra completa de heces refrigeradas con hielo (cuando se le solicite, para realizar otros análisis) en el recipiente para envíos que le suministraremos. Dicho recipiente contiene una serie de compresas de hielo que enfriarán la muestra de manera fiable a -20 °C/-4 °F.</li>
        </ol>
        <p>También puede tomar muestras de otras partes del cuerpo, como el oído, la nariz, la vagina, el cuero cabelludo o la planta del pie.</p>
        <p>Debe enviarnos los bastoncillos o las tarjetas para pruebas de sangre oculta en las heces en el sobre suministrado a través del servicio regular de correo nacional. Las muestras de heces completas deben enviarse al laboratorio Knight Lab en el recipiente para envíos suministrado. </p>
        <p>Se extraerá el ADN de la muestra, y este se amplificará mediante PCR (reacción en cadena de la polimerasa) y se secuenciará para ver qué bacterias contiene la muestra y en qué proporción. Es posible que utilicemos el resto de la muestra para analizar los metabolitos, como las proteínas, o las sustancias químicas derivadas de las bacterias o para tratar de detectar bacterias específicas que nos resulten de interés. Creemos que pasarán dos meses para que usted conozca los resultados del cálculo inicial de la diversidad bacteriana.</p>
        <p>Los resultados se cargarán en su cuenta de American Gut en cuanto estén disponibles.</p>
        <p>Queremos también que nos autorice a utilizar la muestra suministrada o el ADN no humano extraído de dicha muestra (p. ej., el ADN de las bacterias) en futuros estudios. Además, queremos solicitarle su consentimiento para ponernos en contacto con usted por correo electrónico a fin de pedirle más información como seguimiento a las preguntas que haya respondido en el cuestionario.</p>
        <p><b><u>Atención: La secuenciación no tiene fines diagnósticos y no está dirigida al ADN humano.</u></b></p>
        <p style='font-weight: bold;'><i>¿Cuánto tiempo es necesario para realizar cada procedimiento del estudio, cuánto tiempo debe dedicar en total y cuánto durará el estudio?</i></p>
        <p>Tardará 30 minutos o menos para responder el cuestionario en línea. Tardará 5 minutos o menos en tomar cada una de las muestras que vaya a suministrar. Anticipamos que el estudio dure cinco años. No obstante, los resultados estarán a su disposición antes de que el estudio termine (por lo general, en un plazo de 2 meses después de que recibamos la muestra). Puede optar por tomar muestras en más de una ocasión. Si sus datos personales (p. ej., su dirección o estado de salud) cambian, le pedimos que vuelva a introducir voluntariamente sus datos de contacto y/o las respuestas del cuestionario.</p>
        <p style='font-weight: bold;'><i>¿Cuáles son los riesgos relacionados con este estudio?</i></p>
        <p>Las técnicas de toma de muestras se usan desde hace más o menos 10 años, y no se han notificado efectos secundarios al respecto. No examinamos el ADN humano que haya en la muestra, por lo que no obtendremos información personal sobre su genoma. Antes de consignar datos en archivos de acceso público se eliminan todos los datos conocidos de la secuencia humana. El personal del estudio ha tomado precauciones para garantizar que el riesgo de pérdida de la confidencialidad sea mínimo. Si se pusiera en riesgo la confidencialidad, las consecuencias para usted serían mínimas, pues los resultados no son diagnósticos y no repercuten en la decisión de las aseguradoras de darle o no cobertura. <i>(Por lo general, las leyes federales y estatales consideran que es ilegal que las aseguradoras, las aseguradoras para grupos y la mayor parte de los empleadores le discriminen por su información genética. Por norma general, dichas leyes lo protegen de las siguientes formas: a) las aseguradoras y las aseguradoras para grupos no pueden solicitarnos la información genética que obtengamos sobre usted en esta investigación; b) las aseguradoras y las aseguradoras para grupos no pueden usar su información genética para tomar decisiones sobre sus opciones de cobertura o pagos por seguro; c) los empleadores que tengan cinco empleados o más no pueden usar la información genética que obtengamos sobre usted en esta investigación para tomar decisiones de contratación, ascenso o despido ni para definir condiciones laborales.)</i></p>
        <p>Dado que este es un estudio de investigación, puede haber riesgos desconocidos que no podemos prever. Le informaremos de cualquier novedad importante al respecto.</p>
        <p style='font-weight: bold;'><i>¿Cuáles son las alternativas a no participar en este estudio?</i></p>
        <p>El estudio es completamente voluntario y si no participa, no tendrá que hacer frente a ninguna consecuencia. No hay pruebas alternativas.</p>
        <p style='font-weight: bold;'><i>¿Cuáles podrían ser los beneficios de participar?</i></p>
        <p>No obtendrá ningún beneficio directo por participar en este estudio. Creemos que tal vez sienta curiosidad natural por saber qué microbios contiene su muestra y cómo es en comparación con las muestras de otras personas del mismo sexo y edad. De cualquier modo, el investigador obtendrá más información sobre el microbioma humano en situaciones de buena salud y de enfermedad, lo que podría resultar valioso para los investigadores de otros estudios. Tal vez pueda deducir de sus impuestos la contribución al proyecto. Fundrazr, que se encarga de todas las contribuciones financieras, le enviará un recibo.</p>
        <p>Analizaremos todas las muestras para las que se hayan completado el formulario de consentimiento y el cuestionario. Se analizarán las muestras suministradas (incluidas las suyas) y los resultados se publicarán en un artículo científico. Se le enviará un enlace a través del que podrá ver, descargar e imprimir diagramas en alta resolución de sus resultados, aptos para enmarcar. Ni usted ni su médico pueden utilizar los resultados del análisis para confirmar diagnósticos clínicos; no realizamos pruebas de detección de enfermedades infecciosas.</p>
        <p style='font-weight: bold;'><i>¿Puede decidir no participar o retirarse del estudio sin recibir sanciones ni perder beneficios?</i></p>
        <p>La participación en el estudio es completamente voluntaria. Puede negarse a participar o retirarse del estudio en cualquier momento, sin tener que recibir sanciones ni perder los beneficios que le correspondan. Si decide que no desea seguir participando en el estudio, se le pedirá que envíe un mensaje a la dirección de correo electrónico de asistencia del proyecto American Gut para comunicarnos su intención de retirarse del estudio. Si no se ha procesado la muestra, puede solicitar un reembolso, que se tramitará en el sitio en el que realizó su contribución al proyecto.</p>
        <p>Se le notificará cualquier información importante obtenida durante el transcurso del estudio y que pueda afectar a su deseo de seguir participando.</p>
        <p style='font-weight: bold;'><i>¿Se le puede retirar del estudio sin que usted dé su consentimiento?</i></p>
        <p>Es posible que se le retire del estudio si no completa el consentimiento. También se le podría retirar si no sigue las instrucciones que le dé el personal del estudio.</p>
        <p style='font-weight: bold;'><i>¿Se le pagará por participar en este estudio?</i></p>
        <p>No recibirá ninguna remuneración económica por participar en este estudio.</p>
        <p style='font-weight: bold;'><i>¿Hay algún gasto vinculado con la participación en el estudio?</i></p>
        <p>Una vez que se haya inscrito en el proyecto y haya enviado por correo su muestra, no tendrá que pagar nada por participar en el estudio.</p>
        <p style='font-weight: bold;'><i>¿Qué sucede si sufre una lesión como consecuencia directa del estudio?</i></p>
        <p>Si sufre una lesión como consecuencia directa de su participación en este estudio, la Universidad de California le prestará toda la atención médica necesaria para el tratamiento de esas lesiones. Esta universidad no le ofrecerá ningún otro tipo de indemnización por lesiones. Para saber más sobre este tema, llame a la oficina del Programa de protección para investigaciones con seres humanos al (858) 246-4777 para consultar acerca de sus derechos como sujeto de investigación o denunciar cualquier problema relacionado con el estudio.</p>
        <p style='font-weight: bold;'><i>¿Y su confidencialidad?</i></p>
        <p>Se protegerá la confidencialidad de los registros de la investigación en la medida que lo permita la ley. Todos los datos sobre usted que se introduzcan en el sitio web se guardarán en un servidor protegido por contraseña ubicado en el SDSC (San Diego Supercomputer Center), que se encuentra en la UCSD y cuenta con acceso controlado por características biométricas. Los datos financieros de los participantes que contribuyan al proyecto no se pondrán a disposición de los investigadores. El código (que vincula los datos personales del participante con los códigos de barras de las muestras) se guarda en otro servidor protegido por contraseña, al que solo pueden acceder el investigador principal, el investigador secundario, el coordinador de las muestras, el administrador de TI y los programadores de la base de datos. Todos los análisis se realizan con datos anonimizados; los datos que se consignan en archivos públicos para el uso de otros investigadores también se anonimizan. La Junta de Revisión Institucional de la UCSD podrá revisar los registros del estudio.  Tendrá que suministrar datos a través de los que se le podría identificar si se publicaran, como su nombre, su edad, su fecha de nacimiento y su dirección. Hemos hecho todo lo posible para garantizar que nadie pueda identificarle a partir de los datos personales que suministre, pero conservamos información fundamental, como su sexo y su edad, sin poner en riesgo sus datos personales ni la integridad de estos.</p>
        <p>Es posible que debamos denunciar incidentes confirmados o sospechas razonables de maltrato o abandono de niños, adultos dependientes o personas mayores, incluidos el maltrato físico o emocional, el abuso sexual o económico y el abandono. El único modo en que podríamos descubrir dicho maltrato es que lo denuncie el propio participante o su tutor legal, por lo que no es probable que suceda. Si los investigadores se percatan de este tipo de información, podrán denunciarla ante las autoridades pertinentes.</p>
        <p style='font-weight: bold;'><i>¿A quién puede llamar si tiene alguna duda?</i></p>
        <p> Si tiene alguna duda o problemas relacionados con la investigación, puede llamar a Rob Knight al 858-246-1184 o a Dominic Nguyen al 858-534-8739.</p>
        <p>Puede llamar a la oficina del Programa de protección para investigaciones con seres humanos al 858-246-4777 para consultar acerca de sus derechos como sujeto de investigación o denunciar cualquier problema relacionado con el estudio.</p>
        <p style='font-weight: bold;'><i>Firma y consentimiento</i></p>
        <p>Ha recibido una copia de este documento de consentimiento y una copia de la “Declaración de derechos del sujeto experimental” para que las conserve.</p>
        <p>Acepta participar.</p>''',
    'ASSENT_13_17': '''
        <p align='center'>
            <b>University of California, San Diego</b><br/>
            Asentimiento para participar como sujeto de investigación<br/>
            (de 13 a 17 años)
        </p>
        <p align='center'>
            <b>Proyecto American Gut</b>
        </p>
        <p style='font-weight: bold;'><i>¿Quién realiza el estudio, por qué se te ha pedido que participes, cómo se te ha seleccionado y cuál es la cifra aproximada de participantes en el estudio?</i></p>
        <p>El Profesor Rob Knight está llevando a cabo un estudio para saber más sobre el microbioma (microorganismos [seres vivos diminutos, como bacterias] inofensivos o inocuos que viven dentro de tu cuerpo y en la superficie de este). Te hemos invitado a participar en este estudio porque como el resto de los habitantes de este planeta, tú tienes un microbioma único, y mientras más personas de todas las edades estudiemos, mejor podremos comprender cómo nos ayudan o nos perjudican los microorganismos. En el estudio participarán unas 100 000 personas.</p>
        <p style='font-weight: bold;'><i>¿Por qué se realiza este estudio?</i></p>
        <p>El objetivo del estudio es evaluar con mayor precisión las diferencias entre las personas y determinar si dichas diferencias pueden atribuirse al modo de vida, a la dieta, al tipo constitucional, a la edad o a la presencia de enfermedades relacionadas. Los resultados se utilizarán para crear una base de datos que contendrá secuencias y metabolitos de distintas zonas del cuerpo (p. ej., la piel, la boca o el estómago y los intestinos), y detalles acerca de ti (el participante que provee la muestra) que otros investigadores podrán usar cuando necesiten muestras para compararlas con lo que ellos estén estudiando, p. ej., ciertas enfermedades en las que las anomalías estomacales son comunes.</p>
        <p style='font-weight: bold;'><i>¿Qué te sucederá durante estudio y qué procedimientos son de referencia y cuáles son experimentales?</i></p>
        <p>Cuando hayas dado tu consentimiento para participar en el estudio, tendrás que completar un cuestionario en línea en el que responderás a preguntas sobre tu cuerpo, edad, peso, estatura y hábitos alimentarios, así como si has tomado antibióticos, si tienes determinadas enfermedades o si tomas suplementos, como vitaminas. A continuación, tendrás que tomar una muestra de tu cuerpo con el bastoncillo que se suministra con el kit del proyecto American Gut (sobre el estómago y los intestinos de los estadounidenses). En el sobre encontrarás unas instrucciones que te indicarán qué debes hacer. La muestra más común es de material fecal (heces). Para tomarla, inserta las puntas del bastoncillo en papel higiénico usado o pasa las puntas por la superficie de la tarjeta (la tarjeta para pruebas de sangre oculta en las heces). También puedes tomar la muestra de cualquier zona de la piel, de la lengua o la boca, de las fosas nasales, de la cera de los oídos o de la vagina. Puede que se te pida que deposites materia fecal en un recipiente de plástico, que debes colocar debajo de la taza del inodoro. Ninguna de estas muestras o investigaciones nos permitirán diagnosticar enfermedades. Tampoco examinaremos nada en tu propio ADN que también pueda encontrarse en la materia fecal, o en la piel o la saliva. Puede que deseemos ponernos en contacto contigo para hacerte más preguntas acerca de la información que tú o tu mamá/papá/tutor hayan suministrado en el cuestionario.</p>
        <p style='font-weight: bold;'><i>¿Cuánto tiempo es necesario para realizar los procedimientos del estudio, cuánto tiempo debes dedicar en total y cuánto durará el estudio?</i></p>
        <p>Tardarás 30 minutos o menos para responder el cuestionario en línea. Tardarás 5 minutos o menos en tomar cada una de las muestras que vayas a suministrar. En principio, el estudio durará 5 años. No obstante, los resultados estarán a tu disposición antes de que este termine (por lo general, en un plazo de 2 meses después de que recibamos la muestra). Puedes optar por tomar muestras en más de una ocasión. Si tus datos personales (p. ej., tu dirección o estado de salud) cambian, te pedimos que vuelvas a introducir voluntariamente tus datos de contacto o las respuestas del cuestionario para que podamos hacer un seguimiento contigo.</p>
        <p style='font-weight: bold;'><i>¿Cuáles son los riesgos relacionados con este estudio?</i></p>
        <p>Las técnicas de toma de muestras se usan desde hace unos 5 años y no se han notificado efectos secundarios al respecto. No examinaremos tu información genética personal y la información que divulguemos en archivos de datos públicos no contendrá información genética humana, puesto que dicha información se habrá eliminado previamente. El personal del estudio ha tomado precauciones para garantizar que el riesgo de filtración de tus datos personales sea mínimo. Si se publicaran tus datos, las consecuencias serían mínimas, puesto que las pruebas no pueden usarse para elaborar diagnósticos.  $(20)s</p>
        <p style='font-weight: bold;'><i>¿Cuáles son las alternativas a no participar en este estudio?</i></p>
        <p>No estás obligado a participar. No tendrás que hacer frente a ninguna consecuencia.</p>
        <p style='font-weight: bold;'><i>¿Cuáles beneficios podrían anticiparse razonablemente?</i></p>
        <p>No obtendrás ningún beneficio directo por participar en este estudio. El investigador publicará un artículo científico para describir lo que encuentre en las muestras del estudio, incluida la tuya, pero no de forma tal que se pueda saber que habla de tu muestra. Los resultados serán muy valiosos para los investigadores de otros estudios. Se te enviará un enlace a través del cual podrás acceder a tus datos. De este modo, tanto tú como tus padres sabran qué hay en tu muestra en comparación con las muestras de otras personas similares a ti (del mismo sexo y edad).</p>
        <p style='font-weight: bold;'><i>¿Puedes decidir no participar o retirarte del estudio sin recibir sanciones ni perder beneficios?</i></p>
        <p>La participación en el estudio es completamente voluntaria. Puedes negarte a participar o retirarte del estudio en cualquier momento, sin tener que recibir sanciones ni perder los beneficios que te correspondan. Si decides que no deseas seguir participando en el estudio, se te pedirá que envíes un mensaje a la dirección de correo electrónico del proyecto American Gut para comunicarnos tu intención de abandonar el estudio. Se te notificará cualquier información importante obtenida durante el transcurso del estudio y que pueda afectar a tu voluntad para seguir participando.</p>
        <p style='font-weight: bold;'><i>¿Se te puede retirar del estudio sin tu consentimiento?</i></p>
        <p>Es posible que se te retire del estudio si no completas el formulario de consentimiento. También se te podría retirar si no sigues las instrucciones que te suministre el personal del estudio.</p>
        <p style='font-weight: bold;'><i>¿Se te pagará por participar en este estudio?</i></p>
        <p>No recibirás ninguna remuneración económica por participar en este estudio.</p>
        <p style='font-weight: bold;'><i>¿Qué sucede si te lesionas como consecuencia directa del estudio?</i></p>
        <p>Si sufres una lesión o te enfermas como consecuencia directa de este estudio, se te prestará la atención médica que necesites.</p>
        <p style='font-weight: bold;'><i>¿Y la confidencialidad?</i></p>
        <p>Se protegerá la confidencialidad de los registros de la investigación en la medida que lo permita la ley. Todos los datos que se introduzcan en el sitio web se guardarán en un servidor protegido por contraseña ubicado en el SDSC (San Diego Supercomputer Center), que se encuentra en la UCSD y cuenta con acceso controlado por características biométricas. El código (que indica qué código barras se colocó en tu muestra) se guarda en otro servidor protegido por contraseña, al que solo pueden acceder el prof. Knight, el coordinador de las muestras y los programadores de la base de datos. Los datos que se usan en los análisis no indican quién eres. Guardaremos tus datos en un lugar al que podrán acceder otros investigadores, pero no podrán determinar de ningún modo quién eres a partir de dichos datos; no publicaremos, por ejemplo, tu dirección. La Junta de Revisión Institucional de la UCSD podrá revisar los registros del estudio.</p>
        <p style='font-weight: bold;'><i>¿A quién puedes llamar si tienes alguna duda?</i></p>
        <p>Si tienes alguna duda o problemas relacionados con la investigación, puedes llamar a Rob Knight al 858-246-1184 o a Dominic Nguyen al 858-534-8739.</p>
        <p>Puedes llamar a la oficina del Programa de protección para investigaciones con seres humanos al 858-246-4777 para consultar sobre tus derechos como sujeto de investigación o denunciar problemas relacionados con el estudio.</p>
        <p style='font-weight: bold;'><i>Firma y asentimiento</i></p>
        <p>Has recibido una copia de esta hoja de asentimiento y una copia de la “Declaración de derechos del sujeto experimental”, que deberás guardar.</p>
        <p>Aceptas participar.</p>''',
    'ASSENT_7_12': '''
        <p align='center'>
            <b>University of California, San Diego</b><br/>
            Asentimiento para participar como sujeto de investigación<br/>
            (de 7 a 12 años)
        </p>
        <p align='center'>
            <b>Proyecto Gut</b>
        </p>
        <p>El Profesor Rob Knight y su equipo de investigación están realizando un estudio para saber más sobre los billones de diminutos seres vivos, como las bacterias, que viven dentro de tu cuerpo o en la superficie de este. Te preguntan si deseas participar en este estudio porque eres diferente (en buen sentido) de todos los demás, del mismo modo que el resto de las personas son diferentes entre sí.</p>
        <p>Si decides participar en este estudio, esto es lo que sucederá:</p>
        <p>Les pediremos a ti, a tu mamá o a tu papá que tomen una muestra de alguna parte de tu cuerpo (como la piel o la boca) o de tu materia fecal (tomándola del papel higiénico) con un objeto parecido a dos bastoncillos de algodón. A veces necesitamos más materia fecal, por lo que quizá te pidamos que evacúes en un tazón de plástico que se coloca debajo de la silla del inodoro y recibe la materia fecal. Tu mamá o tu papá nos enviará la materia fecal en el tazón.</p>
        <p>A veces los niños no se sienten bien mientras participan en este estudio. Podrías sentir un poco de dolor en el lugar de la piel que se frota con el bastoncillo de algodón. La mayor parte de las personas no sienten este dolor.</p>
        <p>Si sientes algo así o cualquier otra cosa, no dejes de decírselo a tu mamá o a tu papá.</p>
        <p>No es necesario que participes en este estudio de investigación si no quieres. Nadie se molestará contigo si dices que no. Incluso si ahora dices que sí y cambias de opinión después de empezar a participar, podrás retirarte del estudio y nadie se molestará.</p>
        <p>No dejes de hablar con tus padres si tienes alguna duda. Si no te explican bien lo que quieras saber, puedes llamar a Dominic Nguyen para pedirle más información. Su número de teléfono es el 858-534-8739.  También hay un sitio web en Internet en que se explican las cosas: .<a href = "https://www.americangut.org">https://www.americangut.org</a></p>''',
}